all: menu vigenere_encrypt vigenere_decrypt

main: menu.c vigenere_encrypt vigenere_decrypt
	gcc main.c -o main -Wall -std=c99

vigenere_encrypt: vigenere_encrypt.c
	gcc vigenere_encrypt.c -o vigenere_encrypt -Wall -std=c99

vigenere_decrypt: vigenere_decrypt.c
	gcc vigenere_decrypt.c -o vigenere_decrypt -Wall -std=c99
